### ISSUE TITLE
Error when installing with npm

### ISSUE THREAD

**Issue by jebouruama** [1openwindow/azure-openai-node#2]
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @vercel/nft@0.22.6
npm WARN Found: peer graphql@"^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0" from apollo-server-express@2.26.1
npm WARN node_modules/.pnpm/@vercel+nft@0.22.6/node_modules/@vercel/nft/node_modules/apollo-server-express
npm WARN   dev apollo-server-express@"^2.14.2" from @vercel/nft@0.22.6
npm WARN   node_modules/.pnpm/@vercel+nft@0.22.6/node_modules/@vercel/nft
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer graphql@"^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0" from apollo-server-express@2.26.1
npm WARN node_modules/.pnpm/@vercel+nft@0.22.6/node_modules/@vercel/nft/node_modules/apollo-server-express
npm WARN   dev apollo-server-express@"^2.14.2" from @vercel/nft@0.22.6
npm WARN   node_modules/.pnpm/@vercel+nft@0.22.6/node_modules/@vercel/nft
npm ERR! Cannot read properties of null (reading 'matches')

**Comment by 1openwindow** [comment]
@jebouruama This warning message indicates that there is a problem with resolving a dependency while installing the "@vercel/nft" package. it is not about 'azure-openai'.

You can try removing the "node_modules" folder and the "package-lock.json" file and then running "npm install" again to reinstall all dependencies.
