### ISSUE TITLE
Incorrect API Path for chat completion

### ISSUE THREAD

**Issue by jihalpatel** [1openwindow/azure-openai-node#4]
https://github.com/1openwindow/azure-openai-node/blob/b08905569b493d867382aca15fde4d8816ae0530/api.ts#LL1951

It should be
```
localVarPath = `/openai/deployments/${deploymentName}/chat/completions?api-version=2023-03-15-preview`;
```

**Comment by 1openwindow** [comment]
@jihalpatel , thanks for reporting this, it was fixed according to latest /chat/completions at here: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2023-03-15-preview/inference.json
